Repository NIAEFEUP/website-niaefeup-backend, pull requests merged in 2023-03, with the labels that each got.

#118 Added Logging interface
  build.gradle.kts
  src/main/kotlin/pt/up/fe/ni/website/backend/config/Logging.kt
  src/main/kotlin/pt/up/fe/ni/website/backend/controller/ErrorController.kt
  src/test/kotlin/pt/up/fe/ni/website/backend/utils/listeners/DbCleanupListener.kt
Labels: maintainability

#130 Upgrade kotlin to 1.8
  build.gradle.kts
Labels: dependencies

#136 Docs/readme generate docs
  .gitignore
  README.md
  build.gradle.kts
Labels: documentation
